name: CI/CD

env:
  DOCKER_IMAGE_NAME: dnd:${{ github.ref_name }}

on:
  push:
    branches: [main, staging]

jobs:
  ci:
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build dev Docker image
        run: docker build --target dev -t ${{ env.DOCKER_IMAGE_NAME }} .

      - name: Run unit tests
        run: docker run ${{ env.DOCKER_IMAGE_NAME }} pnpm test

      - name: Run database migrations
        run: docker run -e POSTGRES_DATABASE_URL=${{ secrets.POSTGRES_DATABASE_URL }} ${{ env.DOCKER_IMAGE_NAME }} pnpm migrate:prod

  cd:
    needs: ci
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build prod Docker image and push to DockerHub
        uses: docker/build-push-action@v5
        with:
          target: prod
          push: true
          tags: lucasfernandesapp/${{ env.DOCKER_IMAGE_NAME }}

      - name: Trigger deploy hook on Render
        run: curl -X GET ${{ secrets.DEPLOY_HOOK_URL }}
