name: Node.js CI

on:
  push:
    branches: [with-cicd]
  pull_request:
    branches: [with-cicd]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t app:test .

      - name: Run unit tests in Docker container
        run: docker run app:test pnpm test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: lucasfernandesapp/dnd:latest
